/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tradinggui;

import java.net.MalformedURLException;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import se.kth.id2212.bankrmi.Account;
import se.kth.id2212.bankrmi.Bank;
import se.kth.id2212.bankrmi.RejectedException;
import tradingpf.MarketItf;
import tradingpf.TraderImpl;
import tradingpf.TraderItf;

/**
 *
 * @author zoe
 */
public class WindowAccount extends javax.swing.JFrame {

    private Bank bank;
    private MarketItf server;
    private TraderItf client;

    /**
     * Creates new form WindowAccount
     */
    public WindowAccount() {
        initComponents();
    }

    WindowAccount(Bank bank, MarketItf server) {
        initComponents();
        this.bank = bank;
        this.server = server;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateAccount = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        textFieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreateAccount.setText("Create an account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        btnAccount.setText("Start my account");
        btnAccount.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnAccountComponentShown(evt);
            }
        });
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        textFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Name :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnCreateAccount)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAccount)
                    .addComponent(btnAccount))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        // TODO add your handling code here:
        String clientName = textFieldName.getText();
        if (clientName.equals("")) {
            System.out.println("Error, empty name");
            System.exit(1);
        }
        try {
            client = new TraderImpl(clientName);
        } catch (RemoteException ex) {
            Logger.getLogger(WindowAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        Account account = null;
        /*
        try {
            UnicastRemoteObject.exportObject(client);
        } catch (RemoteException ex) {
            Logger.getLogger(WindowAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        try {
            account = bank.getAccount(clientName);
        } catch (RemoteException ex) {
            Logger.getLogger(WindowAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(account == null){
            System.err.println("no account !!");
            System.exit(1);
        }
        WindowRegister nextWindow = 
                new WindowRegister(account, 
                                    server,
                                    client,
                                    clientName);
        nextWindow.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void textFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNameActionPerformed

    private void btnAccountComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnAccountComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccountComponentShown

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        String clientName = textFieldName.getText();
        if (clientName.equals("")) {
            System.out.println("Error, empty name");
            System.exit(1);
        }
        try {
            //Create a new account and make a 100$ deposit on it. Yes, we are nice guys ;)
            Account clientAccount = bank.newAccount(clientName);
            client = new TraderImpl(clientName);
            clientAccount.deposit(100);
            //UnicastRemoteObject.exportObject(client);
            try {
                java.rmi.Naming.rebind(clientName, client);
            } catch (MalformedURLException ex) {
                Logger.getLogger(WindowAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (RemoteException ex) {
            System.out.println(ex);
        } catch (RejectedException ex) {
            System.out.println(ex);
        }
        
        WindowRegister nextWindow = null;
        try {
            nextWindow = new WindowRegister(bank.getAccount(clientName), 
                                             server, 
                                             client, 
                                             clientName);
        } catch (RemoteException ex) {
            Logger.getLogger(WindowAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        nextWindow.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new WindowAccount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textFieldName;
    // End of variables declaration//GEN-END:variables
}
